
[functions.deploy-blueprint]
enabled = true
verify_jwt = true
import_map = "./functions/deploy-blueprint/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/deploy-blueprint/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/deploy-blueprint/*.html" ]

[functions.create-blueprint]
enabled = true
verify_jwt = true
import_map = "./functions/create-blueprint/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/create-blueprint/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/create-blueprint/*.html" ]
