# Generated by Django 4.2.7 on 2025-08-26 05:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        # Step 1: Create the new Space model
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('space_type', models.CharField(choices=[('client', 'Client'), ('internal', 'Internal'), ('demo', 'Demo'), ('testing', 'Testing'), ('staging', 'Staging'), ('production', 'Production')], default='client', max_length=50)),
                ('platform', models.CharField(choices=[('n8n', 'N8N'), ('zapier', 'Zapier'), ('make', 'Make.com'), ('custom', 'Custom')], default='n8n', max_length=50)),
                ('email', models.EmailField(blank=True, help_text='Contact email for this space', max_length=254, null=True)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Platform-specific configuration')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to='api.workspace')),
            ],
        ),
        
        # Step 2: Add constraints to Space model
        migrations.AddConstraint(
            model_name='space',
            constraint=models.UniqueConstraint(fields=('workspace', 'name'), name='unique_workspace_space_name'),
        ),
        
        # Step 3: Add space field to N8nInstance (nullable first)
        migrations.AddField(
            model_name='n8ninstance',
            name='space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='n8n_instances', to='api.space'),
        ),
        
        # Step 4: Add space field to Deployment (nullable first)
        migrations.AddField(
            model_name='deployment',
            name='space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='api.space'),
        ),
        
        # Step 5: Remove old constraints
        migrations.RemoveConstraint(
            model_name='deployment',
            name='unique_automation_client_deployment',
        ),
        migrations.RemoveConstraint(
            model_name='n8ninstance',
            name='unique_client_instance',
        ),
        migrations.RemoveConstraint(
            model_name='n8ninstance',
            name='unique_workspace_master_instance',
        ),
        
        # Step 6: Remove old client fields
        migrations.RemoveField(
            model_name='deployment',
            name='client',
        ),
        migrations.RemoveField(
            model_name='n8ninstance',
            name='client',
        ),
        
        # Step 7: Delete the Client model
        migrations.DeleteModel(
            name='Client',
        ),
        
        # Step 8: Add new constraints
        migrations.AddConstraint(
            model_name='deployment',
            constraint=models.UniqueConstraint(fields=('automation', 'space'), name='unique_automation_space_deployment'),
        ),
        migrations.AddConstraint(
            model_name='n8ninstance',
            constraint=models.UniqueConstraint(condition=models.Q(('space__isnull', True)), fields=('workspace',), name='unique_workspace_master_instance'),
        ),
        migrations.AddConstraint(
            model_name='n8ninstance',
            constraint=models.UniqueConstraint(condition=models.Q(('space__isnull', False)), fields=('space',), name='unique_space_instance'),
        ),
    ]