# Generated by Django 4.2.7 on 2025-08-30 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20250826_0032'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='n8ninstance',
            constraint=models.CheckConstraint(check=models.Q(('workspace__isnull', False), ('space__isnull', False), _connector='OR'), name='n8n_instance_must_have_workspace_or_space'),
        ),
    ]
