# Generated by Django 4.2.7 on 2025-09-29 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_n8ninstance_n8n_instance_must_have_workspace_or_space'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='api.space'),
        ),
    ]
