# Generated by Django 4.2.7 on 2025-09-29 21:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_deployment_space'),
    ]

    operations = [
        migrations.CreateModel(
            name='AINodeType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_type', models.CharField(help_text='n8n node type identifier', max_length=255, unique=True)),
                ('workflow_node_type', models.CharField(help_text='Full node type used in workflows', max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('package', models.CharField(help_text='n8n package name', max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('supports_tokens', models.BooleanField(default=True, help_text='Whether this node type reports token usage')),
                ('provider', models.CharField(help_text='AI provider (openai, anthropic, groq, etc.)', max_length=50)),
                ('token_extraction_method', models.CharField(default='usage', help_text='Method to extract tokens (usage, tokenUsage, etc.)', max_length=50)),
                ('model_path', models.CharField(blank=True, help_text='JSON path to model field in node parameters', max_length=255, null=True)),
                ('typical_models', models.JSONField(default=list, help_text='Common models used with this node type')),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether to include in token analysis')),
            ],
            options={
                'db_table': 'api_ai_node_type',
                'ordering': ['provider', 'display_name'],
            },
        ),
    ]
